In [4]:
# Question 1

import numpy as np
arr=np.random.random((10,1))
print(arr)
print('*'*40)
mean=np.mean(arr)
print(mean)

[[0.08356571]
 [0.35059459]
 [0.76578797]
 [0.67059416]
 [0.73321593]
 [0.2765297 ]
 [0.06527363]
 [0.75377074]
 [0.1030291 ]
 [0.51039213]]
****************************************
0.43127536653264703


In [5]:
# Question 2
arr2=np.random.random((20,1))
print(arr2)
print('*'*40)
std_dev=np.std(arr2)
print(std_dev)
var=std_dev**2
print('*'*40)
print(var)

[[0.47670038]
 [0.32676631]
 [0.40576703]
 [0.4267092 ]
 [0.54688381]
 [0.05315774]
 [0.74267586]
 [0.70307082]
 [0.06088905]
 [0.7152517 ]
 [0.79748334]
 [0.35336488]
 [0.20300664]
 [0.93942894]
 [0.98534193]
 [0.9594957 ]
 [0.93639088]
 [0.11574086]
 [0.31022621]
 [0.83554704]]
****************************************
0.3058341654258216
****************************************
0.09353453674170881


In [8]:
# Question 3

a=np.random.random((10,20))
print(a)
print('*'*40)
b=np.random.random((20,25))
print(b)
print('*'*40)
c=np.matmul(a,b)
print(c)
print('*'*40)
sum=np.sum(c)
print(sum)

[[0.62556695 0.78973153 0.355302   0.74283457 0.9394436  0.58603144
  0.26959327 0.33220722 0.572332   0.87706778 0.33823402 0.69027507
  0.95918187 0.24684756 0.90151282 0.67102026 0.83497761 0.94572423
  0.67821819 0.12685247]
 [0.11903425 0.26635614 0.84101673 0.15092808 0.4983182  0.40690076
  0.44678449 0.76796821 0.64358827 0.44302516 0.84550487 0.28076267
  0.61135846 0.94644779 0.7891901  0.23650579 0.30797509 0.42744415
  0.96785643 0.15641343]
 [0.32869544 0.87085328 0.92766295 0.81090762 0.45641593 0.42043235
  0.38127026 0.00794561 0.10474873 0.9946518  0.74128329 0.53923267
  0.53678136 0.50416267 0.89990608 0.07718596 0.72405949 0.47229011
  0.47040932 0.70048876]
 [0.19373211 0.61504857 0.39571376 0.43569387 0.86675666 0.2610996
  0.97616326 0.67872421 0.81907146 0.67005582 0.16107424 0.6625958
  0.29578906 0.4372625  0.93624388 0.67695137 0.71094381 0.8884394
  0.64272355 0.12541045]
 [0.53994745 0.22910423 0.66466943 0.4046287  0.00509439 0.91826363
  0.32089567 0.7122

In [9]:
# Question 4

A=np.random.random((10,1))
print(A)
print('*'*40)

def func(x):
    return (1/(1+np.exp(-x)))

ans=np.apply_along_axis(func,0,A)
print(ans)


[[0.49712465]
 [0.06036335]
 [0.02836241]
 [0.67199922]
 [0.1585148 ]
 [0.5125313 ]
 [0.36806265]
 [0.73868329]
 [0.98281978]
 [0.86676718]]
****************************************
[[0.62178338]
 [0.51508626]
 [0.50709013]
 [0.66195067]
 [0.53954593]
 [0.62539968]
 [0.59099076]
 [0.67670786]
 [0.72766736]
 [0.70407257]]
