# Accuracy and Metrics -   by RAVINDER SINGH




Question: 1  
Import the dataset from sklearn

Question: 2  
Save X(features) and y(target) as dataframes

Question: 3  
Split the dataset into training and testing sets.

Question: 4  
Use Logistic Regression.

Question: 5  
Print the Following as mentioned in a question
a. Classification accuracy
b. Logarithmic loss
c. R2 metrics
d. Mean absolute error
e. Mean squared error
f. Confusion matrix
g. Classification report

In [2]:
import numpy as np
import pandas as pd

In [13]:
from sklearn.datasets import load_digits


In [14]:
s = load_digits()
s

{'data': array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ..., 10.,  0.,  0.],
        [ 0.,  0.,  0., ..., 16.,  9.,  0.],
        ...,
        [ 0.,  0.,  1., ...,  6.,  0.,  0.],
        [ 0.,  0.,  2., ..., 12.,  0.,  0.],
        [ 0.,  0., 10., ..., 12.,  1.,  0.]]),
 'target': array([0, 1, 2, ..., 8, 9, 8]),
 'target_names': array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 'images': array([[[ 0.,  0.,  5., ...,  1.,  0.,  0.],
         [ 0.,  0., 13., ..., 15.,  5.,  0.],
         [ 0.,  3., 15., ..., 11.,  8.,  0.],
         ...,
         [ 0.,  4., 11., ..., 12.,  7.,  0.],
         [ 0.,  2., 14., ..., 12.,  0.,  0.],
         [ 0.,  0.,  6., ...,  0.,  0.,  0.]],
 
        [[ 0.,  0.,  0., ...,  5.,  0.,  0.],
         [ 0.,  0.,  0., ...,  9.,  0.,  0.],
         [ 0.,  0.,  3., ...,  6.,  0.,  0.],
         ...,
         [ 0.,  0.,  1., ...,  6.,  0.,  0.],
         [ 0.,  0.,  1., ...,  6.,  0.,  0.],
         [ 0.,  0.,  0., ..., 10.,  0.,  0.]],
 
        [[ 0

In [15]:
f = pd.DataFrame(s.data)

In [16]:
f.head()

0    1    2     3     4     5    6    7    8    9  ...    54   55   56  \
0  0.0  0.0  5.0  13.0   9.0   1.0  0.0  0.0  0.0  0.0 ...   0.0  0.0  0.0   
1  0.0  0.0  0.0  12.0  13.0   5.0  0.0  0.0  0.0  0.0 ...   0.0  0.0  0.0   
2  0.0  0.0  0.0   4.0  15.0  12.0  0.0  0.0  0.0  0.0 ...   5.0  0.0  0.0   
3  0.0  0.0  7.0  15.0  13.0   1.0  0.0  0.0  0.0  8.0 ...   9.0  0.0  0.0   
4  0.0  0.0  0.0   1.0  11.0   0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0  0.0   

    57   58    59    60    61   62   63  
0  0.0  6.0  13.0  10.0   0.0  0.0  0.0  
1  0.0  0.0  11.0  16.0  10.0  0.0  0.0  
2  0.0  0.0   3.0  11.0  16.0  9.0  0.0  
3  0.0  7.0  13.0  13.0   9.0  0.0  0.0  
4  0.0  0.0   2.0  16.0   4.0  0.0  0.0  

[5 rows x 64 columns]

In [17]:
target=pd.DataFrame(s.target)
target.head()

0
0  0
1  1
2  2
3  3
4  4

In [18]:
from sklearn.linear_model import LogisticRegression

In [19]:
from sklearn.model_selection import train_test_split

In [20]:
X=f
y=target

In [21]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)


In [22]:
logr=LogisticRegression()

In [23]:
logr.fit(X_train,y_train)

  y = column_or_1d(y, warn=True)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [24]:
pre=logr.predict(X_test)

In [25]:
from sklearn.metrics import classification_report,confusion_matrix,log_loss,mean_absolute_error,mean_squared_error,accuracy_score

In [26]:
print(classification_report(y_test,pre))

             precision    recall  f1-score   support

          0       1.00      0.98      0.99        55
          1       0.93      0.91      0.92        55
          2       0.96      1.00      0.98        52
          3       1.00      0.96      0.98        56
          4       0.98      0.98      0.98        64
          5       0.96      0.93      0.94        73
          6       1.00      0.98      0.99        57
          7       0.98      0.98      0.98        62
          8       0.82      0.96      0.88        52
          9       0.98      0.93      0.95        68

avg / total       0.96      0.96      0.96       594



In [27]:
logr.score(X_test,y_test)

0.9612794612794613

In [28]:
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score,r2_score,mean_absolute_error,mean_squared_error

In [29]:
mean_squared_error(y_test,pre)

0.6279461279461279

In [30]:
print(confusion_matrix(y_test,pre))

[[54  0  0  0  1  0  0  0  0  0]
 [ 0 50  1  0  0  0  0  0  4  0]
 [ 0  0 52  0  0  0  0  0  0  0]
 [ 0  0  0 54  0  1  0  0  1  0]
 [ 0  1  0  0 63  0  0  0  0  0]
 [ 0  2  1  0  0 68  0  1  1  0]
 [ 0  0  0  0  0  1 56  0  0  0]
 [ 0  0  0  0  0  0  0 61  0  1]
 [ 0  1  0  0  0  1  0  0 50  0]
 [ 0  0  0  0  0  0  0  0  5 63]]


In [31]:
r2_score(y_test,pre)

0.922161827178051

In [32]:
mean_absolute_error(y_test,pre)

0.12962962962962962

In [34]:
accuracy_score(y_test,pre)

0.9612794612794613